spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:xmldb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: user
    password: root
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update

logging:
  level:
    org.apache.camel: DEBUG


# Путь к каталогу для загрузки файлов
file:
  watch:
    directory: "src/main/incoming_files"

# Путь к XSLT файлу внутри ресурсов
xslt:
  file: classpath:idoc2order.xsl

# Путь к файлу с примером входящего XML (для тестирования)
example.xml: classpath:original_order.xml